name: Firebase_notification_server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Write SSH Key to file
        run: |
          echo "${{ secrets.SECRATE_KEY }}" > private_key
          chmod 600 private_key  # Set appropriate permissions

      - name: Deploy to Server
        run: |
          ssh -i private_key -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.EC2_IP_ADDRESS }} << 'EOF'
            cd ${{ secrets.BASEPATH }}  # Navigate to your project directory
            echo "Base Path: ${{ secrets.BASEPATH }}"

            git pull origin main # Pull the latest code
          EOF

      - name: Remove the private key file
        run: rm -f private_key